# Generated by Django 3.2.9 on 2021-12-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispSvodkaStoredProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Хранимая процедура',
                'verbose_name_plural': 'Хранимые процедуры',
            },
        ),
        migrations.CreateModel(
            name='NameTabsOfDispSvodka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('stored_procedures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DispSvodkaStoredProcedures', to='disp_svodka.dispsvodkastoredprocedures', verbose_name='Хранимая процедура')),
            ],
            options={
                'verbose_name': 'Имя таблицы дисп. сводки',
                'verbose_name_plural': 'Имена таблиц дисп. сводки',
            },
        ),
        migrations.CreateModel(
            name='TableHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_serial_num', models.IntegerField(default=0)),
                ('field_name', models.CharField(default=None, max_length=20)),
                ('scope', models.CharField(default=None, max_length=20)),
                ('rowspan', models.IntegerField(default=1)),
                ('colspan', models.IntegerField(default=0)),
                ('class_name', models.CharField(default=None, max_length=50)),
                ('table_thead_serial_num', models.IntegerField(default=0)),
                ('name_tabs_of_disp_svodka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.nametabsofdispsvodka')),
            ],
        ),
    ]
