# Generated by Django 3.2.10 on 2021-12-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbFieldNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Имя поля в таблице БД',
                'verbose_name_plural': 'Имена полей в таблице БД',
            },
        ),
        migrations.CreateModel(
            name='DbNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestsToDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_to_db', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('ip', models.CharField(default=None, max_length=15)),
                ('user', models.CharField(default=None, max_length=150)),
                ('password', models.CharField(default=None, max_length=150)),
            ],
            options={
                'verbose_name': 'Cервер БД',
                'verbose_name_plural': 'Сервера БД',
            },
        ),
        migrations.CreateModel(
            name='TabNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(default=None, max_length=2000)),
            ],
            options={
                'verbose_name': 'Имя таблицы дисп. сводки',
                'verbose_name_plural': 'Имена таблиц дисп. сводки',
            },
        ),
        migrations.CreateModel(
            name='THeadFieldTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thead_field_name', models.CharField(max_length=200)),
                ('request_to_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.requeststodb')),
            ],
        ),
        migrations.CreateModel(
            name='TableSiders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(default=0)),
                ('column_serial_num', models.IntegerField(default=0)),
                ('field_value', models.CharField(blank=True, max_length=200)),
                ('rowspan', models.IntegerField(default=1)),
                ('colspan', models.IntegerField(default=1)),
                ('class_name', models.CharField(default=None, max_length=500)),
                ('tsider_serial_num', models.IntegerField(default=0)),
                ('fields_type_and_request_index_dict', models.JSONField(blank=True, null=True)),
                ('db_field_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.dbfieldnames')),
                ('tab_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.tabnames')),
            ],
            options={
                'verbose_name': 'Боковик таблицы',
                'verbose_name_plural': 'Боковики таблиц',
            },
        ),
        migrations.CreateModel(
            name='TableHeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(default=0)),
                ('column_serial_num', models.IntegerField(default=0)),
                ('field_value', models.CharField(blank=True, max_length=200)),
                ('rowspan', models.IntegerField(default=1)),
                ('colspan', models.IntegerField(default=1)),
                ('class_name', models.CharField(default=None, max_length=500)),
                ('thead_serial_num', models.IntegerField(default=0)),
                ('tab_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.tabnames')),
                ('thead_field_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.theadfieldtypes')),
            ],
            options={
                'verbose_name': 'Шапка таблицы',
                'verbose_name_plural': 'Шапки таблиц',
            },
        ),
        migrations.CreateModel(
            name='DbTableNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('db_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.dbnames')),
            ],
            options={
                'verbose_name': 'Имя таблицы БД',
                'verbose_name_plural': 'Имена таблиц БД',
            },
        ),
        migrations.AddField(
            model_name='dbnames',
            name='server_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.servernames'),
        ),
        migrations.AddField(
            model_name='dbfieldnames',
            name='db_table_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='disp_svodka.dbtablenames'),
        ),
    ]
