# Generated by Django 3.2.10 on 2021-12-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disp_svodka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servernames',
            name='ip',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
