# Generated by Django 3.2.9 on 2021-12-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disp_svodka', '0002_remove_tablehead_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablehead',
            name='scope',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
